version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - scribble-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - scribble-net

networks:
  scribble-net:
    driver: bridge
